
package org.donstu.clienttwo;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "https://donstu.org/reservation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.clienttwo.Computer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreeComputers", targetNamespace = "https://donstu.org/reservation", className = "org.donstu.clienttwo.GetFreeComputers")
    @ResponseWrapper(localName = "getFreeComputersResponse", targetNamespace = "https://donstu.org/reservation", className = "org.donstu.clienttwo.GetFreeComputersResponse")
    @Action(input = "https://donstu.org/reservation/ReservationService/getFreeComputersRequest", output = "https://donstu.org/reservation/ReservationService/getFreeComputersResponse")
    public List<Computer> getFreeComputers();

}
